### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by VenomVendor** [magnetsystems/r2m-sdk-android#2] opened 2014-10-28 08:16 UTC
While trying to send request to <kbd>https</kbd> am getting this error.

```
GetRequest: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
GetRequest: onError: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

**Comment by skwokmag** [comment] 2014-10-28 17:04
Hi @VenomVendor,
Thank you for opening this issue. Would you please provide more information (e.g., which rest api is that)? It'd be nice if you can provide a testcase.

**Comment by VenomVendor** [comment] 2014-10-28 17:12
[https://www.mobigyaan.com/api/get_recent_posts/](https://www.mobigyaan.com/api/get_recent_posts/)
with the above url, you will get negative response in browser, I expect the same.

**Comment by skwokmag** [comment] 2014-10-28 18:46
Hi @VenomVendor,
Thank you for your quick response. Would it be possible that you are using the Android Studio plugin 1.0 and you see the messages inside "Event Log" of Android Studio when you press the "Test API" button? Can I also ask what version of Android Studio you are using? Thank you. Appreciate that.

**Comment by VenomVendor** [comment] 2014-10-29 18:10
I get the same error with [1.0.0](https://github.com/magnetsystems/r2m-plugin-android/releases/v1.0.0]).
Am using [Studio Beta 0.8.9](http://tools.android.com/download/studio/canary/0-8-9)

**Comment by skwokmag** [comment] 2014-10-29 19:05
We have released r2m-plugin-android 1.1.0. With it, i have tested:
- Generating the assets and unit test.
- Running the test.
  And I am not able to reproduce the error that you mentioned.
  Would you like to try the new plugin?

**Comment by skwokmag** [comment] 2014-10-29 19:34
Please wait, VenonVendor. Are you on Windows? If so, is this the same/similar issue that you are experiencing: https://github.com/magnetsystems/r2m-plugin-android/issues/5

**Comment by VenomVendor** [comment] 2014-10-30 11:48
Yes, might be the same error, Am using,
- Windows-7 (64 bit)
- Windows-8 (32 bit)

**Comment by skwokmag** [comment] 2014-10-30 18:40
Thank, VenomVendor.
Ok. As this seems to be an issue with the plugin (on windows) instead of in the sdk and there is already an Issue opened correspondingly, so I am closing this.

**Closed as completed by skwokmag** 2014-10-30 18:40 UTC

**Comment by etexier** [comment] 2014-10-30 20:36
Yes, this is an issue that was reported earlier, we are looking at it. The workaround is to perform the REST request separately (through a different REST client, like curl), and copy-pasting the response payload without calling "Test API". At that point, you can generate the API with "generate".
